### ISSUE TITLE
Crear iconos para los Custom Post Types

### ISSUE THREAD

**Issue by davidperezgar** [WPdoaction/animal-shelter#24]
Para definir mejor la interfaz de desarrollo, vamos a crear iconos para cada CPT y añadirlo por código.

**Comment by ohiawins** [comment]
using icons from fontawesome
license https://fontawesome.com/license/free

- dog https://fontawesome.com/icons/dog?s=solid&f=classic
- cat https://fontawesome.com/icons/cat?s=solid&f=classic
